project_id = "azhceastdehujpkyklnb"

[functions.send-email]
verify_jwt = false

[functions.send-consultation-reminders]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = false

[functions.google-calendar-auth]
verify_jwt = false

[functions.google-calendar-event]
verify_jwt = false

[functions.notify-consultation]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.payment-webhook]
verify_jwt = false